# Generated by Django 5.2.15 on 2026-07-02 22:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_membership_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_url', models.URLField(help_text='e.g. a GitHub repository, a project website, or a shared Google Drive / Baidu Pan link.', max_length=500, verbose_name='Link to the project work')),
                ('contribution', models.TextField(verbose_name='My contribution to the project')),
                ('did_well', models.TextField(verbose_name='What I did well')),
                ('to_improve', models.TextField(verbose_name='What can be improved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comments', models.TextField(blank=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_received', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='reports.report')),
            ],
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('author', 'project'), name='one_report_per_student_per_project'),
        ),
        migrations.AddConstraint(
            model_name='peerreview',
            constraint=models.UniqueConstraint(fields=('report', 'reviewee'), name='one_review_per_teammate_per_report'),
        ),
    ]
